# Generated by Django 3.1 on 2021-04-03 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Именование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изоражение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.IntegerField(max_length=9, verbose_name='Цена')),
                ('Бренд', models.CharField(max_length=50)),
                ('Страна бренда', models.CharField(max_length=55)),
                ('Оттенок', models.CharField(max_length=2)),
                ('skin_type', models.CharField(choices=[('for dry', 'Для сухой кожи'), ('for mixed', 'Ддя комбинированного типа кожи'), ('for oily', 'Для жирной кожи'), ('for normal', 'Для нормальной кожи')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForLips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Именование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изоражение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.IntegerField(max_length=9, verbose_name='Цена')),
                ('Бренд', models.CharField(max_length=50)),
                ('Страна бренда', models.CharField(max_length=55)),
                ('products_for', models.CharField(choices=[('creamy', 'Кремовая помада'), ('gloss', 'Блеск'), ('mate', 'Матовая помада'), ('pencil for lips', 'Карандаш для губ')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForEyes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Именование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изоражение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.IntegerField(max_length=9, verbose_name='Цена')),
                ('Бренд', models.CharField(max_length=50)),
                ('Страна бренда', models.CharField(max_length=55)),
                ('products_for', models.CharField(choices=[('shades', 'Тени для век'), ('eyeliner', 'Подводка'), ('glitter', 'Глиттер'), ('Mascara', 'тушь')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForBrows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Именование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изоражение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.IntegerField(max_length=9, verbose_name='Цена')),
                ('Бренд', models.CharField(max_length=50)),
                ('Страна бренда', models.CharField(max_length=55)),
                ('products_for', models.CharField(choices=[('shades', 'Тени для бровей'), ('marker', 'Фломастер'), ('gel', 'Гель'), ('pencil', 'Карандаш')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
