# Generated by Django 3.1 on 2021-04-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_forbrows_foreyes_forlips_foundation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forbrows',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='foreyes',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='forlips',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='foundation',
            name='slug',
        ),
        migrations.AlterField(
            model_name='forbrows',
            name='price',
            field=models.PositiveIntegerField(max_length=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='foreyes',
            name='price',
            field=models.PositiveIntegerField(max_length=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='forlips',
            name='price',
            field=models.PositiveIntegerField(max_length=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='foundation',
            name='price',
            field=models.PositiveIntegerField(max_length=9, verbose_name='Цена'),
        ),
    ]
