# Generated by Django 3.1 on 2021-04-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210403_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='forbrows',
            name='slug',
            field=models.SlugField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='foreyes',
            name='slug',
            field=models.SlugField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='forlips',
            name='slug',
            field=models.SlugField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='foundation',
            name='slug',
            field=models.SlugField(default=1, unique=True),
        ),
    ]
